name = "oblique-strategies-mcp"
main = "src/index.ts"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "yarn build"

# KV Namespace bindings
[[kv_namespaces]]
binding = "KV"
id = "d1ba8031ae76406e8f1c790827ea5099"
preview_id = "364295391af543bfa1d395dbccc0fdd2"
